<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Members List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #f3f4f6;
            color: #374151;
            font-weight: bold;
            padding: 8px;
            text-align: left;
            border: 1px solid #d1d5db;
        }
        td {
            padding: 8px;
            border: 1px solid #d1d5db;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <h1>Members List</h1>
    <p><strong>Generated:</strong> {{ date('d M Y, h:i A') }}</p>
    <p><strong>Total Members:</strong> {{ $members->count() }}</p>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Car Details</th>
                <th>Status</th>
                <th>Joined</th>
            </tr>
        </thead>
        <tbody>
            @foreach($members as $member)
            <tr>
                <td>{{ $member->name }}</td>
                <td>{{ $member->email }}</td>
                <td>{{ $member->phone ?? '-' }}</td>
                <td>
                    @if($member->car_brand || $member->car_model || $member->car_plate)
                        {{ $member->car_brand }} {{ $member->car_model }}<br>
                        {{ $member->car_plate }}
                    @else
                        -
                    @endif
                </td>
                <td>{{ ucfirst($member->status) }}</td>
                <td>{{ $member->created_at->format('d M Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ auth()->user()->organization->name ?? 'Organization' }}</p>
    </div>
</body>
</html>
