<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Transactions List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
        }
        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #f3f4f6;
            color: #374151;
            font-weight: bold;
            padding: 8px;
            text-align: left;
            border: 1px solid #d1d5db;
            font-size: 10px;
        }
        td {
            padding: 6px;
            border: 1px solid #d1d5db;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 9px;
            color: #6b7280;
        }
        .status-completed { color: #059669; font-weight: bold; }
        .status-pending { color: #d97706; font-weight: bold; }
        .status-failed { color: #dc2626; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Transactions List</h1>
    <p><strong>Generated:</strong> {{ date('d M Y, h:i A') }}</p>
    <p><strong>Total Transactions:</strong> {{ $transactions->count() }}</p>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Member</th>
                <th>Type</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Payment Method</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $transaction)
            <tr>
                <td>{{ $transaction->id }}</td>
                <td>
                    {{ $transaction->member->name ?? '-' }}<br>
                    <small>{{ $transaction->member->email ?? '' }}</small>
                </td>
                <td>{{ ucfirst($transaction->type) }}</td>
                <td>RM {{ number_format($transaction->amount, 2) }}</td>
                <td class="status-{{ $transaction->status }}">{{ ucfirst($transaction->status) }}</td>
                <td>{{ $transaction->payment_method ?? '-' }}</td>
                <td>{{ $transaction->created_at->format('d M Y H:i') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ auth()->user()->organization->name ?? 'Organization' }}</p>
    </div>
</body>
</html>
