<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Organizations List</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11px; }
        h1 { text-align: center; color: #333; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f3f4f6; color: #374151; font-weight: bold; padding: 8px; text-align: left; border: 1px solid #d1d5db; font-size: 10px; }
        td { padding: 6px; border: 1px solid #d1d5db; font-size: 10px; }
        tr:nth-child(even) { background-color: #f9fafb; }
        .footer { margin-top: 30px; text-align: center; font-size: 9px; color: #6b7280; }
    </style>
</head>
<body>
    <h1>Organizations List</h1>
    <p><strong>Generated:</strong> {{ date('d M Y, h:i A') }}</p>
    <p><strong>Total Organizations:</strong> {{ $organizations->count() }}</p>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Members</th>
                <th>Status</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            @foreach($organizations as $organization)
            <tr>
                <td>{{ $organization->name }}</td>
                <td>{{ $organization->email }}</td>
                <td>{{ $organization->phone ?? '-' }}</td>
                <td>{{ $organization->address ?? '-' }}</td>
                <td>{{ $organization->members_count }}</td>
                <td>{{ ucfirst($organization->status) }}</td>
                <td>{{ $organization->created_at->format('d M Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Admin Portal</p>
    </div>
</body>
</html>
